---
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          # yamllint disable-line rule:line-length
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install requirements
        run: python -m pip install -r requirements.txt -r requirements_dev.txt

      - name: Run pre-commit
        run: pre-commit run --all-files
